# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b424987841b476b04487f0c139a8261125d3074aefc2b57bcaa55e9fc4261afc4174cc875afae63a2aed89ff7fabc0f302d624a93cfe76d24c18021daa4b21ac

test:
  secret_key_base: 341df1bad4844005b2d379ae8d6101c4acb6fe4c64503b10253b786fc9b1f3d3cea6dc0cd2f468ccd9ae93b2fcc517c85c83a4ea17c82196d8927c328b526347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
